server:
  port: 8080
spring:
  application:
    name: "ScaffoldQuickStart"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: "mongodb://localhost:27017/taller8"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
